# Generated by Django 4.2.3 on 2023-08-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_customer_otpcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
